### ISSUE TITLE
error occurred

### ISSUE THREAD

**Issue by ForrestPi** [Dolorousrtur/ContourCraft#1]
File "/home/xxx/ContourCraft/models/core/base.py", line 18, in __init__                            
    self.inspector.inspect(self.message)
AttributeError: 'Inspector' object has no attribute 'inspect'

could you provide the  version of pytorch_geometric?

**Comment by Dolorousrtur** [comment]
It should work with `torch-geometric==2.4.0`

**Comment by ForrestPi** [comment]
@Dolorousrtur  thanks
